import React from "react";
import {Timeline, Text, Avatar, Button, Tooltip, Popover} from '@mantine/core';

export default function Home() {
    return (
        <div className="flex flex-col items-center justify-center min-h-screen py-2">
            <main className="flex flex-col flex-1 lg:max-w-6xl px-4">

                <h1 className="font-bold text-6xl mb-5">Privacy policy</h1>
                <p className='italic mb-5'>Last updated 06/11/2022</p>
                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>


                <h1 className="mb-5">Interpretation and Definitions</h1>
                <h1 className="mb-5">Interpretation</h1>
                <p>
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h1 className="mb-5">Definitions</h1>
                <p>
                    For the purposes of this Privacy Policy:
                </p>
                <ul className='list-disc ml-5'>
                    <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
                    <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to ECSS.</li>
                    <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li>Country refers to: United Kingdom</li>
                    <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                    <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
                    <li>Service refers to the Website.</li>
                    <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li>Website refers to SotonVerify, accessible from https://sotonverify.link</li>
                    <li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>

                <h1 className="mb-5">Types of Data Collected</h1>
                <h1 className="mb-5">Personal Data</h1>
                <p>
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                    Email address
                    First name and last name
                    Usage Data
                </p>
                <h1 className="mb-5">Usage Data</h1>
                <p>
                    Usage Data is collected automatically when using the Service.
                    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                    We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                </p>
                <h1 className="mb-5">Tracking Technologies and Cookies</h1>
                <p>
                    We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use include:
                    Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                    Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                    We use Session Cookies for the purposes set out below:
                    Necessary / Essential Cookies
                    Type: Session Cookies
                    Administered by: Us
                    Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                </p>
                <h1 className="mb-5">Use of Your Personal Data</h1>
                <p>
                    The Company may use Personal Data for the following purposes:
                    To provide and maintain our Service, including to monitor the usage of our Service.
                    To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
                    For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
                    To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
                    To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
                    To manage Your requests: To attend and manage Your requests to Us.
                    For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
                    For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
                    We may share Your personal information in the following situations:
                    With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
                    For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
                    With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
                    With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.
                    With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
                    With Your consent: We may disclose Your personal information for any other purpose with Your consent.
                </p>
                <h1 className="mb-5">Retention of Your Personal Data</h1>
                <p>
                    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <h1 className="mb-5">Transfer of Your Personal Data</h1>
                <p>
                    Your information, including Personal Data, is processed solely inside of the Universities network.
                    The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of Your data and other personal information.
                </p>
                <h1 className="mb-5">Delete Your Personal Data</h1>
                <p>
                    You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
                    Our Service gives You the ability to delete all the information we store about You from within the Service.
                    You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the manage verification settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
                </p>
                <h1 className="mb-5">Disclosure of Your Personal Data</h1>
                <p>
                    You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
                    Our Service gives You the ability to delete all the information we store about You from within the Service.
                    You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the manage verification settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
                </p>
                <h1 className="mb-5">Law enforcement</h1>
                <p>
                    Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                </p>
                <h1 className="mb-5">Other legal requirements</h1>
                <p>
                    The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                    Comply with a legal obligation
                    Protect and defend the rights or property of the Company
                    Prevent or investigate possible wrongdoing in connection with the Service
                    Protect the personal safety of Users of the Service or the public
                    Protect against legal liability

                </p>
                <h1 className="mb-5">Security of Your Personal Data</h1>

                <p>
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>

                <h1 className="mb-5">Children's Privacy</h1>


                <p>
                    Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
                    If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.

                </p>

                <h1 className="mb-5">Changes to this Privacy Policy</h1>

                <p>
                    We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                    We will let You know via a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

                </p>

                <h1 className="mb-5">Contact Us</h1>

                <p>
                    If you have any questions or concerns about this Privacy Policy, You can contact us:
                    By email: society@ecs.soton.ac.uk
                    Or you can contact SUSU:
                    Phone: 02380 595 200
                    Email: hello@susu.org
                    Or you can contact the University:
                    Phone: +44 (0)23 8059 5000
                    Email: ecs-studentoffice@soton.ac.uk
                </p>
            </main>
        </div>
    );
}