name: Builds Nextjs site

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Copy environment variables
        run: cp .env.example .env

      - run: npm run build
